version: '3.9'

services:

  master:
    container_name: master_cont
    image: postgres:13.2-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: postgres
    volumes:
      - master:/var/lib/postgresql/data

  slave:
    container_name: slave_cont
    image: postgres:13.2-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: postgres
    volumes:
      - slave:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_cont
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  master:
  slave: